### ISSUE TITLE
Awesome-Job,  a question about the ground-truth of this dataset

### ISSUE THREAD

**Issue by saicoco** [bytedance/Portrait-Mode-Video#1]
make this dataset public is a nice job. Can you provide the ground truth of the dataset?

**Comment by youthHan** [comment]
Sorry for the late reply. 

Sure the ground truth will be released this week, together with code for training all the models. Stay tuned. Thanks.

**Comment by youthHan** [comment]
We have uploaded the initial code and data category ID. Please take a look at it for your use. Model checkpoints will come this week.

Check train/val/test split here
https://github.com/bytedance/Portrait-Mode-Video/tree/main/Uniformer/data_list/PMV

**Comment by sailordiary** [comment]
> We have uploaded the initial code and data category ID. Please take a look at it for your use. Model checkpoints will come this week.
> 
> Check train/val/test split here https://github.com/bytedance/Portrait-Mode-Video/tree/main/Uniformer/data_list/PMV

Where can I find the textual descriptions for each of the categories?

**Comment by youthHan** [comment]
@sailordiary Story for the late reply. 
Please stay tuned. The taxonomy with textual descriptions will be available in days.
