### ISSUE TITLE
Can't download videos

### ISSUE THREAD

**Issue by Kerin637** [bytedance/Portrait-Mode-Video#5]
Thank you for your wonderful work! I find that the links in the data/video_links.csv can't be accessed now(502 Bad Gateway). So how to download the videos now? Thanks!

**Comment by youthHan** [comment]
Please have a check at the cached videos from community #7

**Comment by Kerin637** [comment]
> Please have a check at the cached videos from community #7
Thanks !！

**Comment by Kerin637** [comment]
Thanks!!
